---
# tasks file for ansible-role-slurm-compute

- name: Install prereqs for building slurm
  dnf:
    name: "{{ slurm_prereq_packages }}"
    state: latest
    enablerepo: "epel,powertools"

- name: Install slurm compute packages
  dnf:
    name: "{{ slurm_prereq_packages }}"
    state: latest
    enablerepo: "epel,powertools"

- name: Load slurm rpms
  unarchive:
    src: /files/slurm-repo.tar.gz
    dest: "{{ slurm_repo }}"

- name: Install slurm compute packages
  dnf:
    name:
      - #{{ slurm_repo }}/slurm"
      - #{{ slurm_repo }}/slurm-devel"
      - #{{ slurm_repo }}/slurm-libpmi"
      - #{{ slurm_repo }}/slurm-slurmd"


