---
# tasks file for ansible-role-slurm-compute

- name: Install prereqs for building slurm
  dnf:
    name: "{{ slurm_prereq_packages }}"
    state: latest
    enablerepo: "epel,powertools"

- name: Install slurm compute packages
  dnf:
    name: "{{ slurm_prereq_packages }}"
    state: latest
    enablerepo: "epel,powertools"

- name: "Make slurm_repo directory"
  file:
    path: "{{ slurm_repo }}"
    owner: "root"
    group: "root"
    mode: "0755"
    state: directory

- name: "Load slurm rpms"
  unarchive:
    src: slurm-repo.tar.gz
    dest: "{{ slurm_repo }}"
    become: true

- name: Install slurm compute packages
  dnf:
    name:
      - "{{ slurm_repo }}/slurm"
      - "{{ slurm_repo }}/slurm-devel"
      - "{{ slurm_repo }}/slurm-libpmi"
      - "{{ slurm_repo }}/slurm-slurmd"


